ityped.init("#ityped", {
  strings: [
    "Selamat Datang",
    "Salamaik Datang",
    "Wilujeng Sumping",
    "Saleum Teuka",
    "꧋ꦱꦸꦒꦼꦁꦫꦮꦸꦃ꧉",
    "Horas!",
    "Welcome",
    "Willkommen",
    "أهلا وسهلا",
    "いらっしゃいませ",
    "欢迎",
  ],
  typeSpeed: 100,
  startDelay: 200,
  backSpeed: 20,
  backDelay: 2000,
  loop: true,
  cursorChar: "_",
});
